### ISSUE TITLE
Change language by Culture

### ISSUE THREAD

**Issue by ghost1372** [MartinKuschnik/Goji#1]
can you provide a way for change the language without the need for {ApplicationLanguage}?

**Comment by MartinKuschnik** [comment]
There is no need to use the `ApplicationLanguage` markup extension. You can set the `Language` property of the window by your own.

```c#
// ...
mainWindow.Language = new CultureInfo("en");
// ...
````
You can also use your own view model.

**Comment by ghost1372** [comment]
I do not want to use language at all
I prefer change by thread culture
Anyway, thanks for the reply

**Comment by MartinKuschnik** [comment]
You can bind the Language of your windows/controls to your thread culture.
The issue with that is, that the framework need a mechanism to detect that the language has changed. The `Thread` class does not provide an event or any other mechanism for that.

**Comment by ghost1372** [comment]
@MartinKuschnik  Sorry, but the code you said does not work and Language only accepts XmlLanguage 
I meant to have a property called `CurrentCulture ` in `LocalizationProperties.cs` and change the language by changing it:

`LocalizationProperties.CurrentCulture = new CultureInfo("en");`

There is a library that does it, But I could not implement what it did on Goji.

https://github.com/itabaev/wpflocalization/blob/2bbce8fc138b93be43d9ffdb43b76fcecd62ac92/WpfLocalization/Localization/LocalizationManager.cs#L24-L35

Can you help and add this feature as well?

**Comment by MartinKuschnik** [comment]
Can you please explain your whole use case and why you don't like to use the ApplicationLanguage markup extension?

Just setting the thread culture does not work for all cases. Converters will still use the culture provided by the used control and not from the current thread.

**Comment by ghost1372** [comment]
I think using the ApplicationLanguage is not interesting and I do not want language change to be dependent on control.
If ApplicationLanguage  is not used, the language will not change

![1](https://user-images.githubusercontent.com/9213496/112746917-6f176480-8fc7-11eb-8476-a51344a59d1c.gif)

![2](https://user-images.githubusercontent.com/9213496/112746926-78083600-8fc7-11eb-9410-46dc6880804a.gif)

**Comment by MartinKuschnik** [comment]
I did not understand the problem, but maby the following code is solving the problem for you:

```c#
window.Language = XmlLanguage.GetLanguage("en");

// Or

window.Language = XmlLanguage.GetLanguage(Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);
```

**Comment by ghost1372** [comment]
@MartinKuschnik  thank you this code work but There is still a problem
When the language is dependent on the control, I have to set the language separately for all windows
I just want to set the language once and change the whole program
![3](https://user-images.githubusercontent.com/9213496/112747330-041b5d00-8fca-11eb-989d-c4a920e814fa.gif)

**Comment by MartinKuschnik** [comment]
The ApplicationLanguage markup extension is the solution for tat problem 😁

This is the way WPF is designed.

**Comment by ghost1372** [comment]
It only works once and will not be updated if we changing the language and open the window again
Can you provide change the language without the need for control?
![3](https://user-images.githubusercontent.com/9213496/112747648-e9e27e80-8fcb-11eb-9916-5d19dcdfb20c.gif)

**Comment by MartinKuschnik** [comment]
Did you also bound the language to the ApplicationLanguage?

**Comment by ghost1372** [comment]
yes, I also have another question, why is Regex used here? 
https://github.com/MartinKuschnik/Goji/blob/41ac11b2702f7118074263bf988010c7135126f7/Goji/TranslationProviderTypeConverter.cs#L62-L72

Is there a specific reason? 
I changed it as follows and it works without any problems (And the provider will be easier "WpfApp;Folder.Resource")
```
var assemblyName = provider.Substring(0, provider.IndexOf(";"));
string path = provider.ToString().Replace(";", ".");
return new ResxLocalizationProvider(path, Assembly.Load(assemblyName));
```

**Comment by MartinKuschnik** [comment]
I created a small demo app ([GojiDemo.zip](https://github.com/MartinKuschnik/Goji/files/6217082/GojiDemo.zip)). It works for me like expected.

The regex should ensure that the format used for defining the translations is always valid.
Your code works in the case that the format is correct. If not, there is an exception in the designer that is not rely helpful.

**Comment by ghost1372** [comment]
Thanks, the problem was solved
The problem was that I used MainWindow.Language to change the language but you used Application.Current 😀
Thanks, most of my questions were answered, only 2 questions left😁
First, In my system, I have 2 resources Resource.resx and Resource.fa.resx I expect Resource.resx to be the default language but Resource.fa.resx is selected by default. Is it because the region is on Iran?
![Untitled](https://user-images.githubusercontent.com/9213496/112748366-6a0ae300-8fd0-11eb-972c-82c4daad9af7.png)

And the second question is whether it is possible to change the language in the design mode?

**Comment by MartinKuschnik** [comment]
I will try to answer these two questions:

1. In my system, I have 2 resources Resource.resx and Resource.fa.resx I expect Resource.resx to be the default language but Resource.fa.resx is selected by default. Is it because the region is on Iran?

    Yes, windows will always start your application with your system culture. You can check that by having a look to the culture of the current thread directly after application start.

2. And the second question is whether it is possible to change the language in the design mode?

    Yes, you can use `d:XXX="yyy"` to set properties specific to design time. 
You will use `d:Language="{Your Design Time Language}"` to set the language during design time.
 ```xml
<Window x:Class="GojiDemo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:GojiDemo"
        mc:Ignorable="d"
        d:Language="de"
        Language="{ApplicationLanguage}"
        LocalizationProperties.TranslationProvider="resx://GojiDemo;GojiDemo.Translations" >
    
</Window>
```

**Comment by ghost1372** [comment]
@MartinKuschnik excellent ❤ It seems to be more than 2 questions 😁 I create a new issue
