### ISSUE TITLE
Binding Localization

### ISSUE THREAD

**Issue by ghost1372** [MartinKuschnik/Goji#2]
Previously, I used another library for localization, Which in the binding mode provided the following ways:
`
<TextBlock Text="{hc:Localization KeyBinding={Binding SomeProperty}}"/> 
`
or
```
 <TextBlock> 
    <TextBlock.Text> 
        <hc:Localization Key="SomeKey" Arguments="{StaticResource SomeArray}"/>
    </TextBlock.Text>
 </TextBlock> 

```
or
```
 <TextBlock> 
    <TextBlock.Text> 
        <hc:Localization Key="SomeKey"> 
            <Binding Source="{hc:Localization SomeKey2}"/> 
            <Binding Path="SomeProperty" /> 
        </hc:Localization> 
    </TextBlock.Text> 
</TextBlock> 

```
or
```
<TextBlock> 
    <TextBlock.Text> 
         <hc:Localization Key="SomeKey">
            <Binding Path="SomeProperty" />
         </hc:Localization>
    </TextBlock.Text> 
</TextBlock>
```

Are these methods supported in Goji?

The most important question I forgot to ask was how can we Localize a key in Code-Behind?
for example:

`MessageBox.Show(LocalizationManager.Localize("Key").ToString());
`

**Comment by MartinKuschnik** [comment]
Yes, there is a way to do that called `BindingTranslation`.    
Please have a look to the [readme](https://github.com/MartinKuschnik/Goji/blob/master/README.md) for more details:

>## Why multiple markup extension for translation purposes?
>
>Localizing an application will create different kinds of situations with variant requirements. Therefore there are variant markup extensions with different levels of complexity.
>
>- StaticTranslation
>
>  This is the most rudimentary way to localize a text based property.
>  The translation is done only once.
>  
>  *Use Case: Use this type of translation for dialog based views which prevent the user to change the language / culture and are recreated every time.*
>  
>- DynamicTranslation
>
>  This markup extension automatically triggers a retranslation when the control language has changed. 
>  
>  *Use Case: This one should be used if the displayed value should always be up to date. Use this markup extension if you are not sure whether the view stays alive during a language change.*
>  
>- BindingTranslation
>
>  The BindingTranslation is an extended version of the DynamicTranslation and  retranslates the bound key if this has changed.
>  
>  *Use Case: Use this one if you'd like to show a localized text based on an enumeration provided by the view model..*
>
>The following table should highlight the differences a bit more:
>
>|Markup Extension|Updates on language or translator changed?|Updates on translation key changed?|
>|---|---|---|
>|StaticTranslation|No |No |
>|DynamicTranslation|Yes|No |
>|BindingTranslation|Yes|Yes|

And there is also a way to translate in code behind:

```c#
ITranslationProvider translationProvider = new ResxTranslationProvider("...");
translationProvider.ProvideTranslation("Key", culture, ...);
```

**Comment by ghost1372** [comment]
Excellent, I was persuaded to use your code in my library, Do you allow me to use your code? I have to make some changes in your code as well

**Comment by MartinKuschnik** [comment]
Follow the license and I'm fine with it.

**Comment by ghost1372** [comment]
Sure
Thank you again dear friend 
I hope this project will be updated again and get better features ❤
