### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost1372** [MartinKuschnik/Goji#3]
I did a little research, if I use a GPL license the whole project should be published in GPL My project uses MIT license
Is it possible that your project also uses an MIT license? Or another way that i can use your code.

**Comment by MartinKuschnik** [comment]
I could change the license to MIT. Would it be helpful for you?

**Comment by ghost1372** [comment]
Yes Yes thank you

**Comment by MartinKuschnik** [comment]
done

**Comment by MartinKuschnik** [comment]
[v1.1.16](https://www.nuget.org/packages/Goji/1.1.6) is licensed under MIT.

**Comment by ghost1372** [comment]
thank you
