### ISSUE TITLE
usage in setter

### ISSUE THREAD

**Issue by ghost1372** [MartinKuschnik/Goji#4]
Is it possible to use in the setter?

```
<style targettype="TextBlock">
<setter property="Text" value="{DynamicTranslation key}"/>
</style>
```

**Comment by MartinKuschnik** [comment]
This does not work, because `DynamicTranslation` tries to create a binding to setter.

A solution would be to use a control as setter value that uses `DynamicTranslation`.

**Comment by MartinKuschnik** [comment]
Does this helped you?

**Comment by ghost1372** [comment]
yes helped me.😉
But I saw another library that work without problems. It will be good to support this feature in the future.
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/244f915125315ef429cfb724e0e5170cbe5ca102/tests/HelloWorldWPF/MainWindow.xaml#L23

**Comment by MartinKuschnik** [comment]
I think I found a way that solved this problem to 95%.
It would be nice if you could have a look to [Version 1.2.0](https://github.com/MartinKuschnik/Goji/releases/tag/v1.2.0).

Only the case that the translation provider changes cannot be handled.

**Comment by ghost1372** [comment]
thank you it works
